# Generated by Django 4.1.2 on 2022-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "component_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("reference", models.CharField(max_length=255)),
            ],
        ),
    ]
